<a href="https://colab.research.google.com/github/Pratik325/DNNRegressor/blob/master/Regression_Excer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [0]:
df = pd.read_csv("cal_housing_clean.csv")

In [0]:
df.head()

housingMedianAge  totalRooms  ...  medianIncome  medianHouseValue
0              41.0       880.0  ...        8.3252          452600.0
1              21.0      7099.0  ...        8.3014          358500.0
2              52.0      1467.0  ...        7.2574          352100.0
3              52.0      1274.0  ...        5.6431          341300.0
4              52.0      1627.0  ...        3.8462          342200.0

[5 rows x 7 columns]

In [0]:
df.describe()

housingMedianAge    totalRooms  ...  medianIncome  medianHouseValue
count      20640.000000  20640.000000  ...  20640.000000      20640.000000
mean          28.639486   2635.763081  ...      3.870671     206855.816909
std           12.585558   2181.615252  ...      1.899822     115395.615874
min            1.000000      2.000000  ...      0.499900      14999.000000
25%           18.000000   1447.750000  ...      2.563400     119600.000000
50%           29.000000   2127.000000  ...      3.534800     179700.000000
75%           37.000000   3148.000000  ...      4.743250     264725.000000
max           52.000000  39320.000000  ...     15.000100     500001.000000

[8 rows x 7 columns]

In [0]:
x_data = df.drop('medianHouseValue', axis=1)

In [0]:
x_data.shape

(20640, 6)

In [0]:
label = df['medianHouseValue']

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
X_train , x_test , Y_train , y_test = train_test_split(x_data, label, test_size = 0.3)

In [0]:
X_train.shape

(14448, 6)

In [0]:
from sklearn.preprocessing import MinMaxScaler  

In [0]:
scaler = MinMaxScaler()


In [0]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
X_train = pd.DataFrame(data = scaler.transform(X_train) , columns=X_train.columns , index=X_train.index)

In [0]:
x_test = pd.DataFrame(data = scaler.transform(x_test), columns = x_test.columns , index = x_test.index)

In [0]:
x_data.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome'],
      dtype='object')

In [0]:

import tensorflow as tf

In [0]:
house_med = tf.feature_column.numeric_column('housingMedianAge')
total_r = tf.feature_column.numeric_column('totalRooms')
total_b = tf.feature_column.numeric_column('totalBedrooms')
population = tf.feature_column.numeric_column('population')
house_hold = tf.feature_column.numeric_column('households')
med_in = tf.feature_column.numeric_column('medianIncome')

In [0]:
feat_cols = [house_med, total_r, total_b, population, house_hold, med_in]

In [0]:
estimator = tf.estimator.DNNRegressor([10,10,10,10,10,10],feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpy0di6lfc', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f542457ec50>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [0]:
input_func = tf.estimator.inputs.pandas_input_fn(X_train, Y_train , batch_size=10 , num_epochs=1000,shuffle=True)

In [0]:
estimator.train(input_fn=input_func,steps=1000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use `tf.cast` instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Savi

In [0]:
eval_input_fn = tf.estimator.inputs.pandas_input_fn(x_test, y_test , batch_size=10 , num_epochs=1, shuffle = False)

In [0]:
metrics = estimator.evaluate(input_fn=eval_input_fn)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-05-14T11:39:16Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpy0di6lfc/model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2020-05-14-11:39:18
INFO:tensorflow:Saving dict for global step 1000: average_loss = 9023508000.0, global_step = 1000, label/mean = 206226.94, loss = 90118650000.0, prediction/mean = 216669.89
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: /tmp/tmpy0di6lfc/model.ckpt-1000


In [0]:
print(metrics)

{'average_loss': 9023508000.0, 'label/mean': 206226.94, 'loss': 90118650000.0, 'prediction/mean': 216669.89, 'global_step': 1000}


In [0]:
pred_input_fn = tf.estimator.inputs.pandas_input_fn(x_test , batch_size=10 ,
                                                    shuffle = False)

In [0]:
predictions = list(estimator.predict(input_fn=pred_input_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpy0di6lfc/model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [0]:
final_rmse = []
for pred in predictions:
  final_rmse.append(pred['predictions'])

In [0]:
final_rmse

[array([329136.56], dtype=float32),
 array([223339.23], dtype=float32),
 array([201709.42], dtype=float32),
 array([199549.89], dtype=float32),
 array([182305.8], dtype=float32),
 array([213043.33], dtype=float32),
 array([235500.39], dtype=float32),
 array([301535.28], dtype=float32),
 array([235357.89], dtype=float32),
 array([179605.3], dtype=float32),
 array([210533.2], dtype=float32),
 array([202693.86], dtype=float32),
 array([191126.45], dtype=float32),
 array([242185.56], dtype=float32),
 array([220845.42], dtype=float32),
 array([204757.2], dtype=float32),
 array([164650.58], dtype=float32),
 array([154043.12], dtype=float32),
 array([202481.83], dtype=float32),
 array([207577.25], dtype=float32),
 array([227731.31], dtype=float32),
 array([156448.61], dtype=float32),
 array([230181.77], dtype=float32),
 array([219185.08], dtype=float32),
 array([208810.86], dtype=float32),
 array([175912.89], dtype=float32),
 array([235555.2], dtype=float32),
 array([246705.8], dtype=float32)

In [0]:
from sklearn.metrics import mean_squared_error

In [0]:
type(y_test)
#type(final_rmse)

pandas.core.series.Series

In [0]:
mean_squared_error(y_test , final_rmse )**0.5

94992.17691274245